# Generated by Django 5.0.6 on 2024-08-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_epub', '0002_translationversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='is_chapter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='subheading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookitemelement',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
