# Generated by Django 5.0.6 on 2024-08-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_epub', '0004_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
    ]
