# Generated by Django 5.0.6 on 2024-09-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_epub', '0005_alter_answer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='item_id',
            field=models.CharField(max_length=255),
        ),
    ]
